### PR TITLE
Add hiera support.

### PR DESCRIPTION
**Pull request by devdutoit**

### CODE REVIEW

**Comment by mvisonneau** [comment]
I don't think this is necessary to make it work with hiera.

**Comment by tmfarwig-ncsu** [comment]
Correct, it is not necessary to make those changes for it to work with hiera if using puppet 3.0 or later due to automatic parameter lookup.

https://docs.puppetlabs.com/hiera/1/puppet.html#automatic-parameter-lookup

**Comment by saz** [comment]
Please try to fix the tests and I'll consider merging this PR.

**Comment by saz** [comment]
As there is no work on this, I'll close this PR. Feel free to open it again

**Pull request closed without merging**
