### PR TITLE
Only set im_journal_* params for Redhat 7 by default where imjournal is loaded.

### LINKED ISSUE #215: imjournal rate limiting support breaks rsyslog
The imjournal rate limiting directives added in #200 breaks rsyslog in the default configuration because the module "imjournal" is not loaded.  The "imjournal" module is not loaded by default.

CentOS 6.8
rsyslogd 5.8.10, compiled with:
	FEATURE_REGEXP:				Yes
	FEATURE_LARGEFILE:			No
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	Runtime Instrumentation (slow code):	No

> [root@ ~]# service rsyslog restart
Shutting down system logger: Aug  2 14:29:47  kernel: Kernel logging (proc) stopped.
Aug  2 14:29:47  rsyslogd: [origin software="rsyslogd" swVersion="5.8.10" x-pid="24707" x-info="http://www.rsyslog.com"] exiting on signal 15.
                                                           [  OK  ]
Starting system logger:                                    [  OK  ]
[root@ ~]# Aug  2 14:29:47  kernel: imklog 5.8.10, log source = /proc/kmsg started.
Aug  2 14:29:47  rsyslogd: [origin software="rsyslogd" swVersion="5.8.10" x-pid="25258" x-info="http://www.rsyslog.com"] start
Aug  2 14:29:47  rsyslogd: rsyslogd's groupid changed to 4
Aug  2 14:29:47  rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Aug  2 14:29:47  rsyslogd: the last error occured in /etc/rsyslog.conf, line 41:"$ImjournalIgnorePreviousMessages off"
Aug  2 14:29:47  rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Aug  2 14:29:47  rsyslogd: the last error occured in /etc/rsyslog.conf, line 43:"$imjournalRatelimitInterval 600"
Aug  2 14:29:47  rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Aug  2 14:29:47  rsyslogd: the last error occured in /etc/rsyslog.conf, line 45:"$imjournalRatelimitBurst 20000"
Aug  2 14:29:47  rsyslogd-2124: CONFIG ERROR: could not interpret master config file '/etc/rsyslog.conf'. [try http://www.rsyslog.com/e/2124 ]

### PR DESCRIPTION
**Pull request by thlapin**
This fixes #215

### CODE REVIEW

**Comment by benohara** [comment]
This just adds the options with 'undef' which still fails.

**Comment by thlapin** [comment]
@benohara you're correct. I was testing with future parser enabled. I've updated the commit.

**Comment by phamp008** [comment]
Hello @saz , we still see errors when rsyslog restart on EL 6

```
Oct  5 21:09:33 localhost rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Oct  5 21:09:33 localhost rsyslogd: the last error occured in /etc/rsyslog.conf, line 40:"$imjournalStateFile "
Oct  5 21:09:33 localhost rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Oct  5 21:09:33 localhost rsyslogd: the last error occured in /etc/rsyslog.conf, line 41:"$imjournalIgnorePreviousMessages "
Oct  5 21:09:33 localhost rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Oct  5 21:09:33 localhost rsyslogd: the last error occured in /etc/rsyslog.conf, line 42:"$imjournalRatelimitInterval "
Oct  5 21:09:33 localhost rsyslogd-3003: invalid or yet-unknown config file command - have you forgotten to load a module? [try http://www.rsyslog.com/e/3003 ]
Oct  5 21:09:33 localhost rsyslogd: the last error occured in /etc/rsyslog.conf, line 43:"$imjournalRatelimitBurst "
Oct  5 21:09:33 localhost rsyslogd-2124: CONFIG ERROR: could not interpret master config file '/etc/rsyslog.conf'. [try http://www.rsyslog.com/e/2124 ]

```

**Comment by phamp008** [comment]
here is what /etc/rsyslog.conf 

```
# Settings for imjournal (If supported)
$imjournalStateFile
$imjournalIgnorePreviousMessages
$imjournalRatelimitInterval
$imjournalRatelimitBurst

```

**Pull request merged**
